name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    name: Go tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.23.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Verify go.mod
        run: go mod tidy && git diff --exit-code

      - name: Run tests (race)
        run: make test

      - name: Coverage (only internal + main)
        run: |
          INTERNAL_PKGS=$(go list ./internal/... | tr '\n' ',')
          MAIN_PKG=$(go list -f '{{.ImportPath}}' .)
          COVERPKG="${INTERNAL_PKGS}${MAIN_PKG}"

          PKGS=$(go list -f '{{if or (len .TestGoFiles) (len .XTestGoFiles)}}{{.ImportPath}}{{end}}' ./... | grep -v '^$')
          if [ -z "$PKGS" ]; then echo "no test packages"; exit 0; fi

          go test $PKGS -race -covermode=atomic -coverpkg="$COVERPKG" -coverprofile=coverage.out -count=1
          go tool cover -func=coverage.out | tail

      - name: Upload to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
